FROM node:16-alpine AS builder
#ARG CONFIGURATION='dev'

COPY .npmrc /root/.npmrc

ENV PUPPETEER_SKIP_DOWNLOAD='true'

WORKDIR /app
COPY package* ./
#RUN npm install -g -s --no-progress yarn
RUN yarn install

COPY . .

RUN yarn run build && \
    yarn cache clean

FROM nginx:stable-alpine

RUN rm -rf /usr/share/nginx/html/*

COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
