FROM node:16-alpine AS builder
#ARG CONFIGURATION='dev'

COPY .npmrc /root/.npmrc

ENV PUPPETEER_SKIP_DOWNLOAD='true'

WORKDIR /app
COPY package* ./
RUN npm ci

COPY . .

RUN npm run check-types
RUN npm run build

FROM nginx:stable-alpine

RUN rm -rf /usr/share/nginx/html/*

COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
