import { TARIFFS, SERVICES_NAME, SERVICES, PILLS } from '@/modules/services/constants';

export const mockData = {
  globalSearchData: [
    'Как пополнить счет?',
    'Как попасть на сайт Волна Sale?',
    'Как попросить помощи у службы поддержки?',
    'Как попросить Катю о помощи?',
  ],
  tariffs: Object.values(TARIFFS),
};

enum PRICE_TITLE {
  SUBSCRIPTION = 'Абонплата',
  CONNECTION = 'Стоимость подключения',
}

export interface ServicesCardsMockItem {
  title: string;
  price: string;
  period: string | undefined;
  priceTitle: PRICE_TITLE;
  tariff: string[];
  tab: string[];
  filter: string[];
}

export const servicesCardsMock: ServicesCardsMockItem[] = [
  {
    title: 'Дополнительный пакет интернета 5\u00A0Гб',
    price: '55',
    period: undefined,
    priceTitle: PRICE_TITLE.CONNECTION,
    tariff: [TARIFFS.AFFORD, TARIFFS.FLY],
    tab: [SERVICES_NAME[SERVICES.MOBILE], SERVICES_NAME[SERVICES.POPULAR]],
    filter: [PILLS.INTERNET],
  },
  {
    title: 'Дополнительный пакет интернета 15\u00A0Гб',
    price: '80',
    period: undefined,
    priceTitle: PRICE_TITLE.CONNECTION,
    tariff: [TARIFFS.AFFORD, TARIFFS.FLY],
    tab: [SERVICES_NAME[SERVICES.MOBILE], SERVICES_NAME[SERVICES.POPULAR]],
    filter: [PILLS.INTERNET],
  },
  {
    title: 'Дополнительный пакет интернета 25\u00A0Гб',
    price: '125',
    period: undefined,
    priceTitle: PRICE_TITLE.CONNECTION,
    tariff: [TARIFFS.AFFORD, TARIFFS.FLY, TARIFFS.START],
    tab: [SERVICES_NAME[SERVICES.MOBILE], SERVICES_NAME[SERVICES.POPULAR]],
    filter: [PILLS.INTERNET],
  },
  {
    title: 'Безлимитные мессенджеры в поездках по России',
    price: '250',
    period: '/мес.',
    priceTitle: PRICE_TITLE.SUBSCRIPTION,
    tariff: [TARIFFS.AFFORD, TARIFFS.FLY, TARIFFS.START, TARIFFS.WIND],
    tab: [SERVICES_NAME[SERVICES.MOBILE]],
    filter: [PILLS.INTERNET, PILLS.UNLIMITED],
  },
  {
    title: 'Безлимитный YouTube',
    price: '130',
    period: '/мес.',
    priceTitle: PRICE_TITLE.SUBSCRIPTION,
    tariff: [TARIFFS.AFFORD, TARIFFS.FLY, TARIFFS.START, TARIFFS.YOURSELF, TARIFFS.WIND],
    tab: [SERVICES_NAME[SERVICES.MOBILE], SERVICES_NAME[SERVICES.POPULAR]],
    filter: [PILLS.INTERNET, PILLS.UNLIMITED],
  },
  {
    title: 'Безлимитный интернет на день с раздачей',
    price: '40',
    period: '/сут.',
    priceTitle: PRICE_TITLE.SUBSCRIPTION,
    tariff: [TARIFFS.AFFORD, TARIFFS.FLY, TARIFFS.START],
    tab: [SERVICES_NAME[SERVICES.MOBILE], SERVICES_NAME[SERVICES.POPULAR]],
    filter: [PILLS.INTERNET, PILLS.UNLIMITED],
  },
  {
    title: 'Пакет 200\u00A0мин. по Крыму и Краснодарскому краю',
    price: '90',
    period: undefined,
    priceTitle: PRICE_TITLE.CONNECTION,
    tariff: [TARIFFS.AFFORD, TARIFFS.FLY, TARIFFS.START],
    tab: [SERVICES_NAME[SERVICES.MOBILE], SERVICES_NAME[SERVICES.POPULAR]],
    filter: [PILLS.MINUTS],
  },
  {
    title: 'Пакет 400\u00A0мин. по Крыму и Краснодарскому краю',
    price: '130',
    period: undefined,
    priceTitle: PRICE_TITLE.CONNECTION,
    tariff: [TARIFFS.AFFORD, TARIFFS.FLY, TARIFFS.START],
    tab: [SERVICES_NAME[SERVICES.MOBILE], SERVICES_NAME[SERVICES.POPULAR]],
    filter: [PILLS.MINUTS],
  },
  {
    title: 'Безлимитные звонки по Крыму и Краснодарскому краю',
    price: '4',
    period: '/сут.',
    priceTitle: PRICE_TITLE.SUBSCRIPTION,
    tariff: [TARIFFS.AFFORD, TARIFFS.FLY, TARIFFS.START],
    tab: [SERVICES_NAME[SERVICES.MOBILE], SERVICES_NAME[SERVICES.POPULAR]],
    filter: [PILLS.MINUTS, PILLS.UNLIMITED],
  },
  {
    title: 'Умная ТВ-приставка SberBox',
    price: '150',
    period: '/мес.',
    priceTitle: PRICE_TITLE.SUBSCRIPTION,
    tariff: [TARIFFS.AFFORD, TARIFFS.FLY, TARIFFS.START],
    tab: [SERVICES_NAME[SERVICES.INTERNET]],
    filter: [PILLS.SERVICE],
  },
  {
    title: 'Усилитель Wi-Fi сигнала',
    price: '150',
    period: '/мес.',
    priceTitle: PRICE_TITLE.SUBSCRIPTION,
    tariff: [TARIFFS.AFFORD, TARIFFS.FLY, TARIFFS.START],
    tab: [SERVICES_NAME[SERVICES.INTERNET]],
    filter: [PILLS.SERVICE],
  },
  {
    title: 'Статический IP',
    price: '150',
    period: '/мес.',
    priceTitle: PRICE_TITLE.SUBSCRIPTION,
    tariff: [TARIFFS.AFFORD, TARIFFS.FLY, TARIFFS.START],
    tab: [SERVICES_NAME[SERVICES.INTERNET]],
    filter: [PILLS.SERVICE],
  },
  {
    title: 'Viju',
    price: '180',
    period: '/мес.',
    priceTitle: PRICE_TITLE.SUBSCRIPTION,
    tariff: [TARIFFS.AFFORD, TARIFFS.FLY, TARIFFS.START],
    tab: [SERVICES_NAME[SERVICES.INTERNET]],
    filter: [PILLS.SERVICE],
  },
  {
    title: 'Пакет интернета 1\u00A0Гб',
    price: '50',
    period: undefined,
    priceTitle: PRICE_TITLE.CONNECTION,
    tariff: [TARIFFS.START, TARIFFS.WIND],
    tab: [SERVICES_NAME[SERVICES.MOBILE]],
    filter: [PILLS.INTERNET],
  },
  {
    title: 'Пакет интернета 2\u00A0Гб',
    price: '100',
    period: undefined,
    priceTitle: PRICE_TITLE.CONNECTION,
    tariff: [TARIFFS.START, TARIFFS.WIND],
    tab: [SERVICES_NAME[SERVICES.MOBILE]],
    filter: [PILLS.INTERNET],
  },
  {
    title: 'Пакет интернета 5\u00A0Гб',
    price: '200',
    period: undefined,
    priceTitle: PRICE_TITLE.CONNECTION,
    tariff: [TARIFFS.START, TARIFFS.WIND],
    tab: [SERVICES_NAME[SERVICES.MOBILE]],
    filter: [PILLS.INTERNET],
  },
  {
    title: 'Пакет интернета 10\u00A0Гб',
    price: '300',
    period: undefined,
    priceTitle: PRICE_TITLE.CONNECTION,
    tariff: [TARIFFS.START, TARIFFS.WIND],
    tab: [SERVICES_NAME[SERVICES.MOBILE]],
    filter: [PILLS.INTERNET],
  },
  {
    title: 'Автопродление пакета интернета 1\u00A0Гб',
    price: '55',
    period: undefined,
    priceTitle: PRICE_TITLE.CONNECTION,
    tariff: [TARIFFS.START, TARIFFS.WIND],
    tab: [SERVICES_NAME[SERVICES.MOBILE]],
    filter: [PILLS.INTERNET],
  },
  {
    title: 'Автопродление пакета интернета 2\u00A0Гб',
    price: '100',
    period: undefined,
    priceTitle: PRICE_TITLE.CONNECTION,
    tariff: [TARIFFS.START, TARIFFS.WIND],
    tab: [SERVICES_NAME[SERVICES.MOBILE]],
    filter: [PILLS.INTERNET],
  },
  {
    title: 'Автопродление пакета интернета 5\u00A0Гб',
    price: '200',
    period: undefined,
    priceTitle: PRICE_TITLE.CONNECTION,
    tariff: [TARIFFS.START, TARIFFS.WIND],
    tab: [SERVICES_NAME[SERVICES.MOBILE], SERVICES_NAME[SERVICES.POPULAR]],
    filter: [PILLS.INTERNET],
  },
  {
    title: 'Автопродление пакета интернета 10\u00A0Гб',
    price: '300',
    period: undefined,
    priceTitle: PRICE_TITLE.CONNECTION,
    tariff: [TARIFFS.START, TARIFFS.WIND],
    tab: [SERVICES_NAME[SERVICES.MOBILE], SERVICES_NAME[SERVICES.POPULAR]],
    filter: [PILLS.INTERNET],
  },
  {
    title: '3 в 1',
    price: '75',
    period: '/мес.',
    priceTitle: PRICE_TITLE.SUBSCRIPTION,
    tariff: [TARIFFS.START],
    tab: [SERVICES_NAME[SERVICES.MOBILE]],
    filter: [PILLS.INTERNET, PILLS.UNLIMITED],
  },
  {
    title: 'Безлимитный интернет на день',
    price: '30',
    period: '/сут.',
    priceTitle: PRICE_TITLE.SUBSCRIPTION,
    tariff: [TARIFFS.START, TARIFFS.YOURSELF, TARIFFS.WIND],
    tab: [SERVICES_NAME[SERVICES.MOBILE], SERVICES_NAME[SERVICES.POPULAR]],
    filter: [PILLS.INTERNET, PILLS.UNLIMITED],
  },
];
