import { Path } from '@/shared/constants/links';

enum TARIFFS {
  DOITYOURSELF,
  SUNBATHE,
  START,
  FLY,
  CANAFFORD,
  ARCHIVE
}

const TARIFFS_PATHNAME = {
  [TARIFFS.DOITYOURSELF]: Path.tariff.doIt,
  [TARIFFS.SUNBATHE]: Path.tariff.sunbathe,
  [TARIFFS.START]: Path.tariff.start,
  [TARIFFS.FLY]: Path.tariff.fly,
  [TARIFFS.CANAFFORD]: Path.tariff.can,
  [TARIFFS.ARCHIVE]: Path.tariff.archive,
} as const;

const TARIFFS_LABELS = {
  [TARIFFS.DOITYOURSELF]: 'Сделай сам',
  [TARIFFS.SUNBATHE]: 'Загорай',
  [TARIFFS.START]: 'Стартуй',
  [TARIFFS.FLY]: 'Летай',
  [TARIFFS.CANAFFORD]: 'Могу себе позволить',
  [TARIFFS.ARCHIVE]: 'Архив',
} as const;


const TARIFFS_NAME = {
  [TARIFFS.DOITYOURSELF]: 'doIt',
  [TARIFFS.SUNBATHE]: 'sunbathe',
  [TARIFFS.START]: 'start',
  [TARIFFS.FLY]: 'fly',
  [TARIFFS.CANAFFORD]: 'can',
  [TARIFFS.ARCHIVE]: 'archive'
} as const;

const TARIFFS_CONSTANTS = [
  {
    id: TARIFFS.DOITYOURSELF,
    path: TARIFFS_PATHNAME[TARIFFS.DOITYOURSELF],
    label: TARIFFS_LABELS[TARIFFS.DOITYOURSELF],
    name: TARIFFS_NAME[TARIFFS.DOITYOURSELF],
  },
  {
    id: TARIFFS.SUNBATHE,
    path: TARIFFS_PATHNAME[TARIFFS.SUNBATHE],
    label: TARIFFS_LABELS[TARIFFS.SUNBATHE],
    name: TARIFFS_NAME[TARIFFS.SUNBATHE],
  },
  {
    id: TARIFFS.START,
    path: TARIFFS_PATHNAME[TARIFFS.START],
    label: TARIFFS_LABELS[TARIFFS.START],
    name: TARIFFS_NAME[TARIFFS.START],
  },
  {
    id: TARIFFS.FLY,
    path: TARIFFS_PATHNAME[TARIFFS.FLY],
    label: TARIFFS_LABELS[TARIFFS.FLY],
    name: TARIFFS_NAME[TARIFFS.FLY],
  },
  {
    id: TARIFFS.CANAFFORD,
    path: TARIFFS_PATHNAME[TARIFFS.CANAFFORD],
    label: TARIFFS_LABELS[TARIFFS.CANAFFORD],
    name: TARIFFS_NAME[TARIFFS.CANAFFORD],
  },
];

const ARCHIVE = [
  {
    id: TARIFFS.ARCHIVE,
    path: TARIFFS_PATHNAME[TARIFFS.ARCHIVE],
    label: TARIFFS_LABELS[TARIFFS.ARCHIVE],
    name: TARIFFS_NAME[TARIFFS.ARCHIVE],
  },
]

const TARIFFS_AND_ARCHIVE_CONSTANTS = [
  {
    id: TARIFFS.DOITYOURSELF,
    path: TARIFFS_PATHNAME[TARIFFS.DOITYOURSELF],
    label: TARIFFS_LABELS[TARIFFS.DOITYOURSELF],
    name: TARIFFS_NAME[TARIFFS.DOITYOURSELF],
  },
  {
    id: TARIFFS.SUNBATHE,
    path: TARIFFS_PATHNAME[TARIFFS.SUNBATHE],
    label: TARIFFS_LABELS[TARIFFS.SUNBATHE],
    name: TARIFFS_NAME[TARIFFS.SUNBATHE],
  },
  {
    id: TARIFFS.START,
    path: TARIFFS_PATHNAME[TARIFFS.START],
    label: TARIFFS_LABELS[TARIFFS.START],
    name: TARIFFS_NAME[TARIFFS.START],
  },
  {
    id: TARIFFS.FLY,
    path: TARIFFS_PATHNAME[TARIFFS.FLY],
    label: TARIFFS_LABELS[TARIFFS.FLY],
    name: TARIFFS_NAME[TARIFFS.FLY],
  },
  {
    id: TARIFFS.ARCHIVE,
    path: TARIFFS_PATHNAME[TARIFFS.ARCHIVE],
    label: TARIFFS_LABELS[TARIFFS.ARCHIVE],
    name: TARIFFS_NAME[TARIFFS.ARCHIVE],
  },
]

export {
  TARIFFS,
  TARIFFS_PATHNAME,
  TARIFFS_LABELS,
  TARIFFS_NAME,
  TARIFFS_CONSTANTS,
  TARIFFS_AND_ARCHIVE_CONSTANTS,
  ARCHIVE
};
